import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='w-full h-20 text-center   bg-red-700'>
          <ul className='flex justify-end gap-10 pt-8 pr-8  '>
            <li>
              <Link href={'/'} className='text-xl hover:text-black'>
                home
              </Link>
            </li>
          </ul>
        </header>
        {children}
        <footer className='w-full h-20 text-center bg-red-700 pt-8 fixed bottom-0'>
          بخش فوتر
        </footer>
      </body>
    </html>
  )
}
